const puzzles = [
  { category: "In The Office", text: "Copy Machine" },
  { category: "In The Office", text: "Desk & Chair" },
  { category: "In The Office", text: "Laptop Computer" },
  { category: "In The Office", text: "Pens & Pencils" },
  { category: "Occupation", text: "Data Scientist" },
  { category: "Occupation", text: "Software Developer" },
  { category: "Occupation", text: "Web Developer" },
  { category: "Person", text: "Anita Borg" },
  { category: "Person", text: "Bill Gates" },
  { category: "Person", text: "Dorothy Vaughan" },
  { category: "Person", text: "Elon Musk" },
  { category: "Person", text: "Grace Hopper" },
  { category: "Person", text: "Katherine Johnson" },
  { category: "Person", text: "Mary Jackson" },
  { category: "Person", text: "Steve Jobs" },
  { category: "Person", text: "Steve Wozniak" },
  { category: "Phrase", text: "Don't Repeat Yourself" },
  { category: "Phrase", text: "What goes up, must come down" },
  { category: "Phrase", text: "You Aren't Going To Need It" },
  { category: "Place", text: "Chicago, Illinois" },
  { category: "Place", text: "Silicon Valley" },
  {
    category: "Quotation",
    text: '"Be yourself; everyone else is already taken."',
  },
  {
    category: "Quotation",
    text: '"Good artists borrow, great artists steal."',
  },
  { category: "Quotation", text: '"What we think, we become."' },
  { category: "Thing", text: "World Wide Web" },
  { category: "Website", text: "freecodecamp.org" },
];
